const SERVER_CONST = require("./const/server.json");
const FRONTEND_CONST = require("./const/frontend.json");
const ERR_SERVER_RES = require("./const/errRes/server.json");
const ERR_NEWS_RES = require("./const/errRes/news.json");
const ERR_RES = { SERVER: ERR_SERVER_RES, NEWS: ERR_NEWS_RES };

module.exports = genFRONTEND_CONFIG(FRONTEND_CONST, SERVER_CONST, ERR_RES);

function genFRONTEND_CONFIG(FRONTEND_CONST, SERVER_CONST, ERR_RES) {
  FRONTEND_CONST.ALBUM_LIST.PAGINATION = {
    BLOG_COUNT: SERVER_CONST.ALBUM_LIST.PAGINATION.BLOG_COUNT,
    PAGE_COUNT: SERVER_CONST.ALBUM_LIST.PAGINATION.PAGE_COUNT,
  };
  FRONTEND_CONST.ALBUM_LIST.DATASET.VALUE.BLOG_STATUS_PUBLIC =
    SERVER_CONST.BLOG.STATUS.PUBLIC;

  FRONTEND_CONST.USER.PAGINATION = {
    BLOG_COUNT: SERVER_CONST.BLOG.PAGINATION.BLOG_COUNT,
    PAGE_COUNT: SERVER_CONST.BLOG.PAGINATION.PAGE_COUNT,
  };
  FRONTEND_CONST.USER.DATASET.VALUE.BLOG_STATUS_PUBLIC =
    SERVER_CONST.BLOG.STATUS.PUBLIC;

  FRONTEND_CONST.SQUARE.PAGINATION = {
    BLOG_COUNT: SERVER_CONST.SQUARE.PAGINATION.BLOG_COUNT,
    PAGE_COUNT: SERVER_CONST.SQUARE.PAGINATION.PAGE_COUNT,
  };
  FRONTEND_CONST.SQUARE.DATASET.VALUE.BLOG_STATUS_PUBLIC =
    SERVER_CONST.BLOG.STATUS.PUBLIC;

  FRONTEND_CONST._AXIOS = {
    ERR_RES: {
      NEWS_NO_LOGIN: ERR_RES.NEWS.READ.NO_LOGIN,
      NO_LOGIN: ERR_RES.SERVER.RESPONSE.NO_LOGIN,
    },
  };

  return FRONTEND_CONST;
}
